#!/bin/bash
# Content-Verification Enforcement Test: Phase 2 — Test-Provisioned Env Rule + GB_* Scoping (Concern C5)
#
# Issue: .opencode#2244 — full-environment simulation in the tests-v2 harness.
# Phase: red-phase2-gb-scoping — Concern C5, `.opencode/tests-v2/with-test-home`
#        (do_setup/seed_model_config, GB_* scoping) and
#        `.opencode/tests-v2/behaviors/helpers.sh` (__ensure_gitbucket scoping).
#
# SCs covered: SC13, SC16, SC17.
#
# This is a RED-phase test. The GREEN implementation has NOT been applied yet, so the
# assertions below are expected to FAIL (non-zero exit). The GREEN phase will:
#   1. Ensure the test setup (do_setup/seed_model_config/test-home provisioning) sets
#      every required test value (model, config, GitBucket token/host/port when
#      provisioned) rather than inheriting from the parent shell       -> SC13, SC16
#   2. Add a mechanism in with-test-home that scopes the test-provisioned GB_* values
#      (generated by __ensure_gitbucket() in helpers.sh) into the isolated env -i
#      subshell ONLY when BEHAVIOR_NEEDS_REMOTE=1 provisions a test GitBucket
#                                                                       -> SC17(a)
#   3. Keep parent-sourced GB_*/GITBUCKET_PORT out of the env -i allowlist and
#      set-env.sh (no parent leakage)                                   -> SC17(b)
#
# Evidence types: SC13/SC16/SC17 are string — content-verification assertions on
# `.opencode/tests-v2/with-test-home` and `.opencode/tests-v2/behaviors/helpers.sh`.
#
# RED state: Currently `__ensure_gitbucket()` in helpers.sh exports GITBUCKET_PORT,
# GB_HOST, GB_TOKEN within the harness process, but the env -i allowlist in
# with-test-home has NO GB_*/GITBUCKET_PORT pass-through. So even when
# BEHAVIOR_NEEDS_REMOTE=1 provisions a GitBucket, the test-provisioned GB_* values are
# dropped at the env -i boundary and never reach the isolated agent. Phase 2 adds the
# scoping mechanism that makes SC17(a) satisfiable — hence RED.
#
# Usage: bash .opencode/tests-v2/test-2244-phase2-gb-scoping.sh
# Exit:  0 if all checks pass (GREEN), 1 if any check fails (expected RED).

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
while [ "$(basename "$PROJECT_DIR")" != ".opencode" ]; do
    PROJECT_DIR="$(dirname "$PROJECT_DIR")"
done
PROJECT_DIR="$(dirname "$PROJECT_DIR")"

WITH_TEST_HOME="$PROJECT_DIR/.opencode/tests-v2/with-test-home"
HELPERS_SH="$PROJECT_DIR/.opencode/tests-v2/behaviors/helpers.sh"

PASS_COUNT=0
FAIL_COUNT=0

check_pass() {
    local label="$1"
    echo "  PASS: $label"
    PASS_COUNT=$((PASS_COUNT + 1))
}

check_fail() {
    local label="$1"
    local detail="$2"
    echo "  FAIL: $label — $detail" >&2
    FAIL_COUNT=$((FAIL_COUNT + 1))
}

# grep_assert_present: pattern must appear at least once in the file.
grep_assert_present() {
    local label="$1"
    local file="$2"
    local pattern="$3"
    if grep -qF "$pattern" "$file" 2>/dev/null; then
        check_pass "$label"
    else
        check_fail "$label" "pattern '$pattern' not found in $file"
    fi
}

# grep_assert_absent: pattern must NOT appear in the file.
grep_assert_absent() {
    local label="$1"
    local file="$2"
    local pattern="$3"
    if grep -qE "$pattern" "$file" 2>/dev/null; then
        check_fail "$label" "forbidden pattern '$pattern' found in $file"
    else
        check_pass "$label"
    fi
}

echo ""
echo "=== Phase 2 — Test-Provisioned Env Rule + GB_* Scoping (Spec #2244, Concern C5) ==="
echo ""
echo "Target files: $WITH_TEST_HOME"
echo "              $HELPERS_SH"
echo ""

# ---------------------------------------------------------------------------
# SC13 (string): General env-set rule — every required test value is set by the
# test setup (do_setup/seed_model_config/test-home provisioning), never inherited
# from the parent/production shell.
#
# Already GREEN: model + config ARE generated by seed_model_config (opencode.jsonc).
# RED: the test setup has no mechanism to scope the test-provisioned GitBucket
# token/host/port into the isolated env when a test requires them. with-test-home
# contains no GB_* handling at all — the test-provisioned values exported by
# __ensure_gitbucket() are dropped at the env -i boundary instead of being set by
# the test-home provisioning.
# ---------------------------------------------------------------------------
echo "--- SC13: every required test value is set by the test setup ---"

# GREEN-now: model/config generated by seed_model_config, not inherited.
grep_assert_present \
    "SC13: seed_model_config sets the model in opencode.jsonc" \
    "$WITH_TEST_HOME" \
    '"model": "$default_model"'
grep_assert_present \
    "SC13: seed_model_config writes a generated config" \
    "$WITH_TEST_HOME" \
    "opencode.jsonc"

# RED-now: the setup does NOT scope test-provisioned GB_* values into the env.
# Phase 2 GREEN adds a GB_* scoping mechanism in with-test-home so the harness
# setup (not the parent shell) sets GB token/host/port when a test requires them.
grep_assert_present \
    "SC13: test setup scopes test-provisioned GB_TOKEN into the isolated env" \
    "$WITH_TEST_HOME" \
    "GB_TOKEN"
grep_assert_present \
    "SC13: test setup scopes test-provisioned GB_HOST into the isolated env" \
    "$WITH_TEST_HOME" \
    "GB_HOST"

# ---------------------------------------------------------------------------
# SC16 (string): Required test values (GitBucket token/host, model, config)
# generated/set by test setup, never read through from the parent env.
#
# Already GREEN: model/config generated by seed_model_config. The model field
# interpolates $default_model rather than reading a parent model env.
# RED: GitBucket token/host/port are not generated/set by the test setup —
# with-test-home has no GITBUCKET_PORT handling, so the value never reaches the
# isolated env from the setup.
# ---------------------------------------------------------------------------
echo "--- SC16: required test values generated/set by setup, never parent-read ---"

# GREEN-now: model is set by seed_model_config from DEFAULT_TEST_MODEL, not parent-read.
grep_assert_present \
    "SC16: seed_model_config sets model from DEFAULT_TEST_MODEL" \
    "$WITH_TEST_HOME" \
    "DEFAULT_TEST_MODEL"
grep_assert_present \
    "SC16: seed_model_config writes test config to test home" \
    "$WITH_TEST_HOME" \
    "TEST_HOME/.config/opencode/opencode.jsonc"

# RED-now: the setup does not set GITBUCKET_PORT — the test-provisioned port
# generated by __ensure_gitbucket() never reaches the isolated env. Phase 2 GREEN
# adds the scoping so the setup generates/sets the GitBucket port value.
grep_assert_present \
    "SC16: test setup sets test-provisioned GITBUCKET_PORT in the isolated env" \
    "$WITH_TEST_HOME" \
    "GITBUCKET_PORT"

# ---------------------------------------------------------------------------
# SC17 (string): No parent-sourced GB_* leaks into the isolated test env; the
# test-env constants (GB_HOST, GB_REPO, GB_PROTOCOL, GITBUCKET_PORT) are always set
# to the harness's constants, and GB_TOKEN (the credential secret) is scoped only to
# a provisioned test GitBucket instance (BEHAVIOR_NEEDS_REMOTE=1).
#
# SC17(b) — parent-sourced GB_* excluded from the env -i allowlist and set-env.sh
# (no "${GB_TOKEN:-}" / "${GB_HOST:-}" / "${GITBUCKET_PORT:-}" pass-through). These
# PASS and MUST stay absent.
#
# SC17(a) — when BEHAVIOR_NEEDS_REMOTE=1 provisions a test GitBucket, the
# test-provisioned GB_* values generated by __ensure_gitbucket() reach the isolated
# env via the BEHAVIOR_NEEDS_REMOTE-guarded GB_ENV_ARGS/GB_TOKEN pass-through. The
# test-env constants are always set (GREEN), so SC17 asserts their markers are
# present and that parent-sourced passthrough remains absent.
# ---------------------------------------------------------------------------
echo "--- SC17: no parent-sourced GB_*; constants always set, GB_TOKEN guarded ---"

# SC17(b): parent-sourced GB_* must NOT propagate via the allowlist or set-env.sh.
grep_assert_absent \
    "SC17b: allowlist has no parent-sourced GB_TOKEN passthrough" \
    "$WITH_TEST_HOME" \
    'GB_TOKEN=\${GB_TOKEN'
grep_assert_absent \
    "SC17b: allowlist has no parent-sourced GB_HOST passthrough" \
    "$WITH_TEST_HOME" \
    'GB_HOST=\${GB_HOST'
grep_assert_absent \
    "SC17b: allowlist has no parent-sourced GITBUCKET_PORT passthrough" \
    "$WITH_TEST_HOME" \
    'GITBUCKET_PORT=\${GITBUCKET_PORT'
grep_assert_absent \
    "SC17b: set-env.sh has no parent-sourced GB_*" \
    "$WITH_TEST_HOME" \
    '^export GB_'

# RED-now: SC17(a) — no mechanism scopes test-provisioned GB_* into the env -i
# subshell when BEHAVIOR_NEEDS_REMOTE=1. Phase 2 GREEN adds a BEHAVIOR_NEEDS_REMOTE-
# guarded GB_* scoping block in with-test-home. Asserting presence of a guarded
# scope marker that does not yet exist.
grep_assert_present \
    "SC17a: with-test-home scopes GB_* when BEHAVIOR_NEEDS_REMOTE provisions GitBucket" \
    "$WITH_TEST_HOME" \
    "GB_TOKEN"
grep_assert_present \
    "SC17a: with-test-home scopes GB_HOST when GitBucket is provisioned" \
    "$WITH_TEST_HOME" \
    "GB_HOST"
grep_assert_present \
    "SC17a: with-test-home scopes GITBUCKET_PORT when GitBucket is provisioned" \
    "$WITH_TEST_HOME" \
    "GITBUCKET_PORT"

# SC17(a) helpers-side: __ensure_gitbucket() MUST scope GB_* to the test instance
# (test-generated, not parent). This is GREEN-now: __ensure_gitbucket() generates
# and exports GB_HOST (http://localhost:$port) and GB_TOKEN (generated token).
grep_assert_present \
    "SC17a: __ensure_gitbucket sets GB_HOST to the test instance URL" \
    "$HELPERS_SH" \
    'export GB_HOST="http://localhost:$port"'
grep_assert_present \
    "SC17a: __ensure_gitbucket sets GB_TOKEN to a test-generated token" \
    "$HELPERS_SH" \
    'export GB_TOKEN="$token"'

echo ""
echo "=== Results ==="
echo "PASSED: $PASS_COUNT"
echo "FAILED: $FAIL_COUNT"
echo ""
if [ "$FAIL_COUNT" -gt 0 ]; then
    echo "RED phase expected: Phase 2 (test-provisioned env rule + GB_* scoping) not yet implemented."
    echo "The test setup does not yet scope test-provisioned GB_*/GITBUCKET_PORT into the"
    echo "isolated env -i subshell when BEHAVIOR_NEEDS_REMOTE=1 provisions a test GitBucket."
    echo "The values exported by __ensure_gitbucket() in helpers.sh are dropped at the"
    echo "env -i boundary because with-test-home has no GB_* scoping mechanism."
    echo ""
    exit 1
fi
exit 0
